# Generated by Django 4.2.7 on 2025-12-08 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('verification', '0001_initial'),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('bid_created', 'Bid Created'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('bid_closed', 'Bid Closed'), ('bid_completed', 'Bid Completed'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('rating_received', 'Rating Received'), ('system', 'System Notification')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bids.bid')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='verification.verificationdocument')),
                ('related_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='offers.offer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
