# Generated by Django 4.2.7 on 2026-01-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('bid_created', 'Bid Created'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('offer_not_selected', 'Offer Not Selected'), ('bid_awarded', 'Bid Awarded'), ('bid_closed', 'Bid Closed'), ('bid_completed', 'Bid Completed'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('rating_received', 'Rating Received'), ('system', 'System Notification')], max_length=30),
        ),
    ]
