# Generated by Django 4.2.7 on 2025-12-08 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('business_license', 'Business License'), ('tax_clearance', 'Tax Clearance Certificate'), ('company_registration', 'Company Registration Document'), ('identity_document', 'Identity Document'), ('company_business_registration', 'Company Business Registration Doc'), ('company_business_license', 'Company Business License Doc'), ('company_competency_certificate', 'Company Competency Certificate Doc'), ('company_tax_clearance', 'Company Tax Clearance Doc'), ('company_vat_certificate', 'Company VAT Certificate Doc'), ('plc_registration', 'PLC Registration Doc'), ('plc_business_license', 'PLC Business License Doc'), ('plc_competency_certificate', 'PLC Competency Certificate Doc'), ('plc_tax_clearance', 'PLC Tax Clearance Doc'), ('plc_vat_certificate', 'PLC VAT Certificate Doc'), ('truck_business_licence', 'Truck Business Licence')], max_length=50)),
                ('file', models.FileField(help_text='Verification document file', upload_to='user_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
