# Generated by Django 4.2.7 on 2025-12-24 13:26

import apps.verification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(help_text='Verification document file', upload_to=apps.verification.models.verification_document_upload_path),
        ),
    ]
