# Generated by Django 4.2.7 on 2025-12-08 04:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('origin', models.CharField(max_length=255)),
                ('origin_address', models.TextField(blank=True)),
                ('destination', models.CharField(max_length=255)),
                ('destination_address', models.TextField(blank=True)),
                ('weight', models.CharField(max_length=100)),
                ('cargo_type', models.CharField(max_length=100)),
                ('special_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid_files', models.FileField(blank=True, help_text='Optional files attached to the bid', null=True, upload_to='bid_files/')),
                ('selected_offer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'shipper'}, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
