# Generated by Django 4.2.7 on 2025-12-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_delivery_completed'),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='selected_offer_id',
        ),
        migrations.AddField(
            model_name='bid',
            name='selected_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_bids', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
