# Generated by Django 4.2.7 on 2025-12-31 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_remove_bid_selected_offer_id_bid_selected_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
