# Generated by Django 4.2.7 on 2026-01-04 06:30

import apps.bids.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_biddeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='offers_deadline',
            field=models.DateField(default=apps.bids.models.default_offers_deadline, help_text='Deadline for submitting offers'),
        ),
    ]
